{"responseData": 
	{"results":
	 [{
	 		"GsearchResultClass":"GwebSearch",
	   	"unescapedUrl":"http://www.test.com/",
	   	"url":"http://www.test.com/",
	   	"visibleUrl":"www.test.com",
	   	"cacheUrl":"http://www.google.com/search?q\u003dcache:S9XHtkEncW8J:www.test.com",
	   	"title":"\u003cb\u003eTest\u003c/b\u003e.com Web Based \u003cb\u003eTesting\u003c/b\u003e and Certification Software v2.0",
	   	"titleNoFormatting":"Test.com Web Based Testing and Certification Software v2.0",
	   	"content":"Easily Author and Administer your own Training Content, \u003cb\u003eTests\u003c/b\u003e, and Certification   Programs Online. \u003cb\u003eTest\u003c/b\u003e.com is Web Based Software."},
	   {
	   	"GsearchResultClass":"GwebSearch","unescapedUrl":"http://speakeasy.net/speedtest/","url":"http://speakeasy.net/speedtest/","visibleUrl":"speakeasy.net","cacheUrl":"http://www.google.com/search?q\u003dcache:YJmLCxSKKn8J:speakeasy.net","title":"Speakeasy - Speed \u003cb\u003eTest\u003c/b\u003e","titleNoFormatting":"Speakeasy - Speed Test","content":"Speakeasy, a Best Buy Company, offers superior Voice over IP (VoIP), T1, DSL and   a range of broadband services cust omized for small businesses."},{"GsearchResultClass":"GwebSearch","unescapedUrl":"http://en.wikipedia.org/wiki/Test","url":"http://en.wikipedia.org/wiki/Test","visibleUrl":"en.wikipedia.org","cacheUrl":"http://www.google.com/search?q\u003dcache:dxrXMu4BMrYJ:en.wikipedia.org","title":"\u003cb\u003eTest\u003c/b\u003e - Wikipedia, the free encyclopedia","titleNoFormatting":"Test - Wikipedia, the free encyclopedia","content":"\u003cb\u003eTest\u003c/b\u003e, \u003cb\u003eTEST\u003c/b\u003e or Tester may refer to: \u003cb\u003eTest\u003c/b\u003e (assessment), an assessment intended to   measure the respondents\u0026#39; knowledge or other abilities; Physical fitness \u003cb\u003etest\u003c/b\u003e \u003cb\u003e...\u003c/b\u003e"},{"GsearchResultClass":"GwebSearch","unescapedUrl":"http://www.bandwidthplace.com/","url":"http://www.bandwidthplace.com/","visibleUrl":"www.bandwidthplace.com","cacheUrl":"","title":"Bandwidth Place | Internet Speed \u003cb\u003eTest\u003c/b\u003e","titleNoFormatting":"Bandwidth Place | Internet Speed Test","content":"\u003cb\u003eTest\u003c/b\u003e your Internet Speed. \u003cb\u003eTest\u003c/b\u003e your Bandwidth Speed."}],"cursor":{"pages":[{"start":"0","label":1},{"start":"4","label":2},{"start":"8","label":3},{"start":"12","label":4},{"start":"16","label":5},{"start":"20","label":6},{"start":"24","label":7},{"start":"28","label":8}],"estimatedResultCount":"52800000","currentPageIndex":0,"moreResultsUrl":"http://www.google.com/search?oe\u003dutf8\u0026ie\u003dutf8\u0026source\u003duds\u0026start\u003d0\u0026hl\u003den\u0026q\u003dTest"}}, "responseDetails": null, "responseStatus": 200}