processResults(
{"responseData": 
	{"results":
		[{"GsearchResultClass":
		"GwebSearch"
,"unescapedUrl":"http://www.imdb.com/title/tt0295701/"
,"url":"http://www.imdb.com/title/tt0295701/"
,"visibleUrl":"www.imdb.com"
,"cacheUrl":"http://www.google.com/search?q\u003dcache:vGOEzteOhXEJ:www.imdb.com"
,"title":"\u003cb\u003exXx\u003c/b\u003e (2002)"
,"titleNoFormatting":"xXx (2002)"
,"content":"Directed by Rob Cohen. With Vin Diesel, Asia Argento, Marton Csokas. Xander Cage   is an extreme sports athelete recruited by the government on a special \u003cb\u003e...\u003c/b\u003e"
},{"GsearchResultClass":"GwebSearch"
,"unescapedUrl":"http://en.wikipedia.org/wiki/.xxx"
,"url":"http://en.wikipedia.org/wiki/.xxx"
,"visibleUrl":"en.wikipedia.org"
,"cacheUrl":"http://www.google.com/search?q\u003dcache:7sJ5x_DTyTcJ:en.wikipedia.org"
,"title":".\u003cb\u003exxx\u003c/b\u003e - Wikipedia, the free encyclopedia"
,"titleNoFormatting":".xxx - Wikipedia, the free encyclopedia"
,"content":".\u003cb\u003exxx\u003c/b\u003e (known as \u0026quot;dot triple-X\u0026quot;) is a top level domain whose application has been   approved for review by ICANN. Final ICANN approval is still pending. \u003cb\u003e...\u003c/b\u003e"
},{"GsearchResultClass":"GwebSearch"
,"unescapedUrl":"http://www.sonypictures.com/homevideo/xxx/"
,"url":"http://www.sonypictures.com/homevideo/xxx/"
,"visibleUrl":"www.sonypictures.com"
,"cacheUrl":"http://www.google.com/search?q\u003dcache:tNNHSxgVuZAJ:www.sonypictures.com"
,"title":"\u003cb\u003exXx\u003c/b\u003e - Official DVD Site"
,"titleNoFormatting":"xXx - Official DVD Site"
,"content":"But when crack NSA Agent Gibbsons convinces Cage to infiltrate a ruthless   Russian crime ring, this new breed of secret agent (codename: \u003cb\u003eXXX\u003c/b\u003e) takes down   the \u003cb\u003e...\u003c/b\u003e"
},{"GsearchResultClass":"GwebSearch"
,"unescapedUrl":"http://www.pornhub.com/"
,"url":"http://www.pornhub.com/"
,"visibleUrl":"www.pornhub.com"
,"cacheUrl":"http://www.google.com/search?q\u003dcache:kDf5QNWK_eYJ:www.pornhub.com"
,"title":"Free Porn Videos \u0026amp; Pussy Movies- Sex Videos, Porno, Porn Tube, \u003cb\u003eXXX\u003c/b\u003e \u003cb\u003e...\u003c/b\u003e"
,"titleNoFormatting":"Free Porn Videos \u0026amp; Pussy Movies- Sex Videos, Porno, Porn Tube, XXX ..."
,"content":"Free porn sex videos \u0026amp; pussy movies. Porn hub is the ultimate \u003cb\u003exxx\u003c/b\u003e porn,sex and   pussy tube, download sex videos or stream free \u003cb\u003exxx\u003c/b\u003e and free pussy movies."
}],"cursor":{"pages":[{"start":"0"
,"label":1},{"start":"4"
,"label":2},{"start":"8"
,"label":3},{"start":"12"
,"label":4},{"start":"16"
,"label":5},{"start":"20"
,"label":6},{"start":"24"
,"label":7},{"start":"28"
,"label":8}],"estimatedResultCount":"11500000"
,"currentPageIndex":0,"moreResultsUrl":"http://www.google.com/search?oe\u003dutf8\u0026ie\u003dutf8\u0026source\u003duds\u0026start\u003d0\u0026hl\u003den\u0026q\u003dXXX"}}, "responseDetails": null, "responseStatus": 200}
)